version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync ./build/ s3://my-react-app-bucket1212/ --delete

artifacts:
  files:
    - '**/*'
  base-directory: build
